language: node_js
node_js:
- lts/*
before_script:
- npm run build
- npm run knex:migrate
- npm run knex:seed
deploy:
  provider: heroku
  app: ecoleta-server
  api_key:
    secure: Ka0LQ4mlws9m1Cmgz4g8XfFCFLKTSmwWfy7SgjaXYkhGEnHgKUCaYIY7mWPxLrnnDaeHWqWmv0fjyaTYjiHZSIMfzH3XTeDE7HckbpGPbzZyZ5hju4n8Umpq8mLMwEIB2ThqRT8TgzRcdUYIMQLzQPxYwVP4I3YIDIRBRkzDkWHMyI5nlpbuueZyIxA3L68I4f+AAvShIc8wIyliWA8lgslmf3tTYWNmMdydfS3A+N059YZvu+IiWZp8O2rD7ngL1DpMMsYqdLayRakZG6a6eJLuOtFCbuMc1j6gl8NzxUZErdfxh3CWDY6yF/oOAryU/caWqzg9HaAIsJVgwvTST2u6GG6A94mI2/S66V/JyjgEYl5tdfa7mDxNrNENHm9YImqZ5ymn1h+9toxJ9PIxmTp7vU0SHskQFmsO2HjvOYOZDPM4rdWDlh7p91vUl45WacPyh5o4fXqZ1RDS8x2uzHzHw0C1t99lnO172x30hoSLHlcxeCwldK+AH4N6C8x9Ye4N/jjbsU6s0K1oBQvW1WRLC5UasT//sTncT9nZFudAidTAoc75rqrC41viLwSGMwbpnObl0Cxt73GGVqALVYwq1QpQUNanleGooQnyZVHSaQal3XyqdgxgPBcVy7LlhP8FeGI8yztHhYWsRzcbqso2fRRlW3iKEsSnp+x7no4=
